### ISSUE TITLE
parse Slack @usernames in message body

### ISSUE THREAD

**Issue by christophermlne** [thesoftwarejedi/TSJ.Gemini.Slack#21]
Currently @mentions are ignored when the incoming JSON is parsed by Slack. 

Slack will parse @mentions if 'link_names":1 is present in the JSON payload as per:

```curl -X POST --data-urlencode 'payload={"channel": "#gemini", "link_names":1, "username": "@myUserName", "text": "@parseThisName: This message contains a user name that will be parsed", "icon_emoji": ":ghost:"}' https://hooks.slack.com/services/<TOKEN>```

**Comment by christophermlne** [comment]
see 'Parsing Modes' here: https://api.slack.com/docs/formatting

**Comment by thesoftwarejedi** [comment]
Saar (from Countersoft) did this back in August it turns out.  I haven't done a rebuild, but I accepted his merge request.  It should be built into the latest Gemini version
